# Generated by Django 3.2.8 on 2021-11-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('telephones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефоны')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Факс')),
                ('site_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сайт')),
                ('site_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сайт')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('dealer_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес дилеров')),
                ('dealer_site', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сайт дилеров')),
                ('dealer_email', models.EmailField(max_length=254, verbose_name='Электронная почта дилеров')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
