# Generated by Django 3.2.8 on 2021-11-03 07:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionspage_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionspage',
            name='question_answer',
            field=wagtail.core.fields.StreamField([('question_answer_block', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.RichTextBlock(label='Вопрос')), ('answer', wagtail.core.blocks.RichTextBlock(label='Ответ'))]))], blank=True, verbose_name='Документация с описанием'),
        ),
    ]
