# Generated by Django 3.2.8 on 2021-11-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('gallery', '0002_auto_20211103_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerytheme',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='gallerytheme',
            name='gallery_name',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='gallery_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название темы галереи'),
        ),
        migrations.AddField(
            model_name='gallerytheme',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='gallerytheme',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
