# Generated by Django 3.2.8 on 2021-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_eventcard_eventnewspages_footer_header_newscard_productcard_productcardpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='path_to_page',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок страницы продукции'),
        ),
    ]
