# Generated by Django 3.2.8 on 2021-11-01 14:16

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productcard_path_to_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='article',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='текст статьи'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='article_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название статьи'),
        ),
    ]
