# Generated by Django 3.2.8 on 2021-11-02 06:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='article_image_third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='третье изображение'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='article_part_third',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Содержание статьи ч.2'),
        ),
    ]
