# Generated by Django 3.2.8 on 2021-11-01 14:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='product_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='описание продукции'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=10, null=True, verbose_name='Название продукции')),
                ('diameter_nominal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Название продукции')),
                ('diameter_outside', models.CharField(blank=True, max_length=10, null=True, verbose_name='Название продукции')),
                ('diameter_insulation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Название продукции')),
                ('insulation_thickness', models.CharField(blank=True, max_length=10, null=True, verbose_name='Название продукции')),
                ('insulation_mass', models.CharField(blank=True, max_length=10, null=True, verbose_name='Название продукции')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_data', to='products.productpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
