# Generated by Django 3.2.8 on 2021-11-01 15:42

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211101_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttabledata',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_data', to='products.producttablepage'),
        ),
    ]
