# Generated by Django 3.2.8 on 2021-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producttabledata_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttabledata',
            name='product_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название продукции'),
        ),
    ]
