# Generated by Django 3.2.8 on 2021-11-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_producttabledata_product_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTableData',
            new_name='TableDataProduct1',
        ),
        migrations.RenameModel(
            old_name='ProductTablePage',
            new_name='TablePageProduct1',
        ),
    ]
