# Generated by Django 3.2.8 on 2021-11-01 17:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211101_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePageProduct2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Характеристики отводов',
                'verbose_name_plural': 'Характеристики отводов',
            },
        ),
        migrations.CreateModel(
            name='TableDataProduct2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название продукции')),
                ('diameter_nominal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Диаметр условный трубопровода, Ду')),
                ('diameter_outside', models.CharField(blank=True, max_length=10, null=True, verbose_name='Диаметр наружный трубопровода, Дтр')),
                ('diameter_insulation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Диаметр изоляции, Диз')),
                ('insulation_thickness', models.CharField(blank=True, max_length=10, null=True, verbose_name='Толщина изоляции, ?из')),
                ('bend_radius', models.CharField(blank=True, max_length=10, null=True, verbose_name='Радиус отвода, R')),
                ('lever_arm_length', models.CharField(blank=True, max_length=10, null=True, verbose_name='Длина плеча отвода, L')),
                ('theoretical_mass', models.CharField(blank=True, max_length=10, null=True, verbose_name='Теоретическая масса отвода 90° в ППМ изоляции, кг')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_data', to='products.tablepageproduct1')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
