# Generated by Django 3.2.8 on 2021-11-01 17:37

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_tabledataproduct2_tablepageproduct2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledataproduct1',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_1_data', to='products.tablepageproduct1'),
        ),
        migrations.AlterField(
            model_name='tabledataproduct2',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_2_data', to='products.tablepageproduct2'),
        ),
    ]
