# Generated by Django 3.2.8 on 2021-11-01 18:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211101_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePageProduct3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Характеристики шаровых кранов',
                'verbose_name_plural': 'Характеристики шаровых кранов',
            },
        ),
        migrations.CreateModel(
            name='TableDataProduct3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название продукции')),
                ('diameter_nominal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Условный диаметр, Ду')),
                ('rod_diameter', models.CharField(blank=True, max_length=10, null=True, verbose_name='Диаметр штока, d')),
                ('diameter_insulation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Диаметр изоляции, Диз')),
                ('insulation_thickness', models.CharField(blank=True, max_length=10, null=True, verbose_name='Толщина изоляции, ?из')),
                ('h_min', models.CharField(blank=True, max_length=10, null=True, verbose_name='Н мин')),
                ('lever_arm_length', models.CharField(blank=True, max_length=10, null=True, verbose_name='Длина плеча отвода, L')),
                ('mass', models.CharField(blank=True, max_length=10, null=True, verbose_name='Масса изолированного шарового крана, кг г')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_3_data', to='products.tablepageproduct3')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
